### ISSUE TITLE
Looks a little weird

### ISSUE THREAD

**Issue by NicoCharrua** [blueblock6/CleanStartpos#1]
![Screenshot](https://github.com/blueblock6/CleanStartpos/assets/55714525/27c51a48-be50-469c-a3b9-c41307dd13a1)

Some of the settings are in the way of the text, and the checkboxes on the right have gone off the menu. Maybe because of wide screen?

v1.0.1, Pixel 6A, Android 14, Geode v2.0.0-beta.19

Nice mod btw :)

**Comment by blueblock6** [comment]
Fixed in 1.0.2, updated version should be on the index soon, thanks for pointing it out!
