### ISSUE TITLE
Crash in level options

### ISSUE THREAD

**Issue by Kingminer7** [blueblock6/CleanStartpos#2]
When trying to open the select gamemode ui, it crashes.

[temp_424008000061638.dmp.txt](https://github.com/user-attachments/files/15808843/temp_424008000061638.dmp.txt)

https://github.com/blueblock6/CleanStartpos/assets/100500023/a0c2264a-c09c-45ed-a344-dbbf16236bc0

**Comment by blueblock6** [comment]
Fixed 1.2.2, thanks for notifying me
