### ISSUE TITLE
Crashlog

### ISSUE THREAD

**Issue by TuckerMcNa** [blueblock6/CleanStartpos#5]
Apologies if I am not supposed to put this here;

2024-08-06T17:29:08+0100
Whoopsies! An unhandled exception has occurred.
It appears that the crash occurred while executing code from the "blueblock6.cleanstartpos" mod. Please submit this crash report to its developers (BlueBlock6) for assistance.

== Geode Information ==
Loader Version: v3.4.0
Loader Commit: a533b5f
Bindings Commit: de6a02b
Installed mods: 15
Problems: 0

== Exception Information ==
Faulty Module: C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\blueblock6.cleanstartpos\blueblock6.cleanstartpos.dll
Faulty Mod: Clean Startpos v1.2.4 (blueblock6.cleanstartpos)
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 00007FFC514E5F3F (blueblock6.cleanstartpos.dll + 5f3f)
Number Parameters: 2
Crashed thread: Main

== Stack Trace ==
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\blueblock6.cleanstartpos\blueblock6.cleanstartpos.dll + 5f3f
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 859c2 (geode::Loader::Impl::executeMainThreadQueue + 242 | /home/runner/work/geode/geode/loader/src/loader/LoaderImpl.cpp:879)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 5ec7d (geode::modifier::AsStaticFunction_update<FunctionQueue,void (FunctionQueue::*)(float)>::Impl<void (FunctionQueue::*)(float)>::function + 29 | /home/runner/work/geode/geode/build/bindings/bindings/Geode/modify/CCScheduler.hpp:115)
 - 00000164F0AE4472 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + bbc24 (cocos2d::CCDirector::drawScene + 36)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + bc33b
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 72cd2 (cocos2d::CCApplication::run + 1122)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 4a2d69
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 2453da (gdMainHook + 554 | /home/runner/work/geode/geode/loader/src/platform/windows/main.cpp:167)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 4a415a
 - C:\WINDOWS\System32\KERNEL32.DLL + 17374 (BaseThreadInitThunk + 20)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 4cc91 (RtlUserThreadStart + 33)

== Register States ==
RAX: 0000000000000000
RBX: 0000000000000000
RCX: 00000164f4bb9510
RDX: 00000164fb88b770
RBP: 0000000000000000
RSP: 00000011c1cffe20
RDI: 0000000000000000
RSI: 0000000000000000
RIP: 00007ffc58ebcc91
R8:  00000164ed864200
R9:  0000000000000001
R10: 0000000000008000
R11: 00000011c1cff350
R12: 0000000000000000
R13: 0000000000000000
R14: 0000000000000000
R15: 0000000000000000

== Installed Mods ==
x | [v1.2.4] blueblock6.cleanstartpos
x | [v1.0.3] capeling.startpos_switcher
x | [v4.2.5] cvolton.betterinfo
x | [v1.0.0] cvolton.level-id-api
x | [v1.2.0-beta.2] cvolton.misc_bugfixes
x | [v1.7.1] geode.custom-keybinds
x | [v3.4.0] geode.loader
x | [v1.13.1] geode.node-ids
x | [v1.1.0] hjfod.backups
x | [v6.7.0] hjfod.betteredit
x | [v1.2.1] hjfod.gmd-api
x | [v1.0.0] hjfod.trashcan
x | [v1.3.7-beta.2] m336.levelinfo
x | [v1.0.0-beta.34] minemaker0430.gddp_integration
x | [v1.1.20] syzzi.click_between_frames

**Comment by TuckerMcNa** [comment]
The crash is probably also related to the 'Start Pos Switcher' mod, as the crash only occured when I spammed the keys to switch start position, but it said it had something to do with this mod, so I'm leaving this here for now.

**Comment by blueblock6** [comment]
Update it to the latest version (1.2.5) and it should stop crashing
